### ISSUE TITLE
XCTU Ubuntu compatibility

### ISSUE THREAD

**Issue by volandoc** [monstrenyatko/butler-xbee-gateway#1]
Please add XCTU usage manual workaround for Linux: 
http://www.downtowndougbrown.com/2013/03/getting-x-ctu-in-wine-to-detect-your-serial-ports/

Maybe we can use: http://blog.arduino.cc/2012/03/08/easy-cross-platform-configurator-for-xbee-modules/

**Comment by monstrenyatko** [comment]
I don't have a XBee module to check this tool. I'll do it later when I buy one.
XBeeGateway supports ubuntu. But you need to configure the XBee modules on any other platform that is supported by XCTU.

**Comment by monstrenyatko** [comment]
@volandoc 
[Digi](https://www.digi.com) released official [XCTU](https://www.digi.com/products/xbee-rf-solutions/xctu-software/xctu) utility for linux.
