### ISSUE TITLE
Other bridges of butler smart gateway

### ISSUE THREAD

**Issue by reggie-gu** [monstrenyatko/butler-xbee-gateway#11]
Hi, 
I understand that this is a xbee-tcp bridge for a butler smart gateway. Is it easy to integrate with other bridges ? Do you know where is possible to find the general implementation of the gateway ?

Thanks,

**Comment by monstrenyatko** [comment]
This application allows you to pass data from XBEE to tcp.

I am using it to connect my sensors with MQTT broker so sensors do not have TCP stack and just send raw MQTT packets to XBEE in transparent mode via software serial (https://github.com/monstrenyatko/butler-arduino-sensor).

You can easily send any other data over XBEE and configure gateway for routing to any other port.

I am not clearly understand your question. What kind of other bridges do you need?

**Comment by reggie-gu** [comment]
In particular, I was looking for a CoAp/UDP bridge in addition to the XBEE/TCP one. In general, any other bridges that may be available for butler smart gateway. As there is available documentation for this gateway in open-platforms.eu, or in the butler homepage, I believed that there were more implementations, or at least an official, general one with different types of bridges (and your implementation complemented it). However, I could not find it.

**Comment by monstrenyatko** [comment]
Oh now it is more clear.
Unfortunately my project is not related to "BUTLER SmartGateways" (www.iot-butler.eu).
